### ISSUE TITLE
ciddo.py scan

### ISSUE THREAD

**Issue by yussufhajjaj** [ptrebert/sciddo#14]
Hello!

I am trying to use sciddo on my chromHMM bed files, when I reach the scan step, an error message appears that I have to identify --scoring/-sc matrix to be used, I really don't understand this parameter since my bioinformatics knowledge is very limited, can you please lead me in this? And thanks in advance..

Yussuf

**Comment by ptrebert** [comment]
Hi Yussuf,

the scoring parameter / scoring matrix specifies the pairwise scores that are used to compute the (dis-) similarity between the chromatin states. The subcommand `score` is used to add (at least one) scoring matrix to the sciddo dataset.

+Peter

**Comment by yussufhajjaj** [comment]
**Dear Peter, 
I created a scoring matrix, and re ran the score command, and the scan, and now I have this error message, and unfortunately I don't understand the problem, can you please check it?** 

Regards, Yussuf.

score --scoring /data/home.local/oz92afip/sciddo_scoring_trial/socring_mx/scoring_matrix.tsv
Traceback (most recent call last):
  File "/home.local/oz92afip/programs/miniconda3/envs/sciddo/lib/python3.6/site-packages/scidlib-1.0.0-py3.6-lin                                             ux-x86_64.egg/scidlib/cmd_scan.py", line 835, in prepare_scan_params
    _ = hdf[os.path.join(ROOT_SCORE, s, 'matrix')]
  File "/home.local/oz92afip/programs/miniconda3/envs/sciddo/lib/python3.6/site-packages/pandas/io/pytables.py",                                              line 479, in __getitem__
    return self.get(key)
  File "/home.local/oz92afip/programs/miniconda3/envs/sciddo/lib/python3.6/site-packages/pandas/io/pytables.py",                                              line 695, in get
    raise KeyError('No object named %s in the file' % key)
KeyError: 'No object named /data/home.local/oz92afip/sciddo_scoring_trial/socring_mx/scoring_matrix.tsv/matrix i                                             n the file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/programs/miniconda3/envs/sciddo/lib/python3.6/site-packages/scidlib-1.0.0-py3.6-linux-x86_64.egg/EGG-INFO/scripts/sciddo.py", line 163, in <module>
    exc = cli_args.execute(cli_args, logger)
  File "/programs/miniconda3/envs/sciddo/lib/python3.6/site-packages/scidlib-1.0.0-py3.6-linux-x86_64.egg/scidlib/cmd_scan.py", line 887, in _run_cmd_scan
    scan_jobs, md_params, ka_params, binsize = prepare_scan_params(args, pairs, group1, group2, baselengths, log                                             ger)
  File "/programs/miniconda3/envs/sciddo/lib/python3.6/site-packages/scidlib-1.0.0-py3.6-linux-x86_64.egg/scidlib/cmd_scan.py", line 839, in prepare_scan_params
    'of dataset {}: {}'.format(s, os.path.basename(args.dataset), sk))
AssertionError: Scoring scheme with name "sciddo_scoring_trial/socring_mx/scoring_matrix.tsv" is not part of dataset sciddo_ZEB1.h5: ['/scoring/scoring_matrix/matrix', '/scoring/scoring_matrix/param                                             eters']
2021-05-21 09:51:14,985 - ERROR: Properly handled shutdown upon error:

Scoring scheme with name "/sciddo_scoring_trial/socring_mx/scoring_matrix.tsv" is not part of dataset sciddo_ZEB1.h5: ['/scoring/scoring_matrix/matrix', '/scoring/scoring_matrix/parameters']

**Comment by yussufhajjaj** [comment]
**Dear Peter,
I created a scoring matrix, and re ran the score command, and the scan, and now I have this error message, and unfortunately I don't understand the problem, can you please check it?

Regards, Yussuf.**

score --scoring /sciddo_scoring_trial/socring_mx/scoring_matrix.tsv
Traceback (most recent call last):
File "/programs/miniconda3/envs/sciddo/lib/python3.6/site-packages/scidlib-1.0.0-py3.6-lin ux-x86_64.egg/scidlib/cmd_scan.py", line 835, in prepare_scan_params
_ = hdf[os.path.join(ROOT_SCORE, s, 'matrix')]
File "/programs/miniconda3/envs/sciddo/lib/python3.6/site-packages/pandas/io/pytables.py", line 479, in getitem
return self.get(key)
File "/programs/miniconda3/envs/sciddo/lib/python3.6/site-packages/pandas/io/pytables.py", line 695, in get
raise KeyError('No object named %s in the file' % key)
KeyError: 'No object named /sciddo_scoring_trial/socring_mx/scoring_matrix.tsv/matrix i n the file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/programs/miniconda3/envs/sciddo/lib/python3.6/site-packages/scidlib-1.0.0-py3.6-linux-x86_64.egg/EGG-INFO/scripts/sciddo.py", line 163, in
exc = cli_args.execute(cli_args, logger)
File "/programs/miniconda3/envs/sciddo/lib/python3.6/site-packages/scidlib-1.0.0-py3.6-linux-x86_64.egg/scidlib/cmd_scan.py", line 887, in _run_cmd_scan
scan_jobs, md_params, ka_params, binsize = prepare_scan_params(args, pairs, group1, group2, baselengths, log ger)
File "/programs/miniconda3/envs/sciddo/lib/python3.6/site-packages/scidlib-1.0.0-py3.6-linux-x86_64.egg/scidlib/cmd_scan.py", line 839, in prepare_scan_params
'of dataset {}: {}'.format(s, os.path.basename(args.dataset), sk))
AssertionError: Scoring scheme with name "sciddo_scoring_trial/socring_mx/scoring_matrix.tsv" is not part of dataset sciddo_ZEB1.h5: ['/scoring/scoring_matrix/matrix', '/scoring/scoring_matrix/param eters']
2021-05-21 09:51:14,985 - ERROR: Properly handled shutdown upon error:

Scoring scheme with name "/sciddo_scoring_trial/socring_mx/scoring_matrix.tsv" is not part of dataset sciddo_ZEB1.h5: ['/scoring/scoring_matrix/matrix', '/scoring/scoring_matrix/parameters']
