### ISSUE TITLE
stats (counts) cannot be computed 

### ISSUE THREAD

**Issue by quirinmanz** [ptrebert/sciddo#9]
Hello,

I have analyzed the HepG2 and K562 cell lines from ENCODE with ChromHMM. Now I would like to use SCIDDO to identify differential chromatin states.

1. My output folder from ChromHMM looks like a classic ChromHMM output folder:
_ls HM_TF-SRSF1-PTBP1/
emissions_20.png	  HepG2_20_overlap.svg		       HepG2_20_RefSeqTSS_neighborhood.svg  K562_20_overlap.svg			K562_20_RefSeqTSS_neighborhood.svg  transitions_20.txt
emissions_20.svg	  HepG2_20_overlap.txt		       HepG2_20_RefSeqTSS_neighborhood.txt  K562_20_overlap.txt			K562_20_RefSeqTSS_neighborhood.txt  webpage_20.html
emissions_20.txt	  HepG2_20_RefSeqTES_neighborhood.png  HepG2_20_segments.bed		    K562_20_RefSeqTES_neighborhood.png	K562_20_segments.bed
HepG2_20_dense.bed.gz	  HepG2_20_RefSeqTES_neighborhood.svg  K562_20_dense.bed.gz		    K562_20_RefSeqTES_neighborhood.svg	model_20.txt
HepG2_20_expanded.bed.gz  HepG2_20_RefSeqTES_neighborhood.txt  K562_20_expanded.bed.gz		    K562_20_RefSeqTES_neighborhood.txt	transitions_20.png
HepG2_20_overlap.png	  HepG2_20_RefSeqTSS_neighborhood.png  K562_20_overlap.png		    K562_20_RefSeqTSS_neighborhood.png	transitions_20.svg_

2. As first step with sciddo I used the convert command:
_sciddo.py --debug --workers 16 convert -col -ssg ../chromhmm/HM_TF-SRSF1-PTBP1/ -csz ../../ChromHMM/CHROMSIZES/hg38.txt -mde ../chromhmm/HM_TF-SRSF1-PTBP1/model_20.txt -o HM_TF-SRSF1-PTBP1
2020-08-13 16:49:52,167 - DEBUG: Configuration written to my_path/sciddo/20200813-164952-pmip_SCIDDO_convert_cfg.json
2020-08-13 16:49:52,169 - DEBUG: Reading state emission probabilities from file ../chromhmm/firstAll_noeCLIP/model_20.txt
2020-08-13 16:49:52,197 - DEBUG: Creating output folder
2020-08-13 16:49:52,198 - DEBUG: Start processing files - 48 jobs in total
2020-08-13 16:49:53,919 - DEBUG: Finished job 1 of 48: state/HepG2_20_segments/chrX
2020-08-13 16:49:53,977 - DEBUG: Finished job 2 of 48: state/HepG2_20_segments/chr13
2020-08-13 16:49:54,050 - DEBUG: Finished job 3 of 48: state/HepG2_20_segments/chr15
2020-08-13 16:49:54,358 - DEBUG: Finished job 4 of 48: state/HepG2_20_segments/chr14
2020-08-13 16:49:54,415 - DEBUG: Finished job 5 of 48: state/HepG2_20_segments/chr9
2020-08-13 16:49:54,459 - DEBUG: Finished job 6 of 48: state/HepG2_20_segments/chr11
2020-08-13 16:49:54,478 - DEBUG: Finished job 7 of 48: state/HepG2_20_segments/chr10
2020-08-13 16:49:54,496 - DEBUG: Finished job 8 of 48: state/HepG2_20_segments/chr12
2020-08-13 16:49:54,513 - DEBUG: Finished job 9 of 48: state/HepG2_20_segments/chr8
2020-08-13 16:49:54,683 - DEBUG: Finished job 10 of 48: state/HepG2_20_segments/chr4
2020-08-13 16:49:54,733 - DEBUG: Finished job 11 of 48: state/HepG2_20_segments/chr7
2020-08-13 16:49:54,747 - DEBUG: Finished job 12 of 48: state/HepG2_20_segments/chrY
2020-08-13 16:49:54,779 - DEBUG: Finished job 13 of 48: state/HepG2_20_segments/chr5
2020-08-13 16:49:54,801 - DEBUG: Finished job 14 of 48: state/HepG2_20_segments/chr18
2020-08-13 16:49:54,991 - DEBUG: Finished job 15 of 48: state/HepG2_20_segments/chr3
2020-08-13 16:49:55,006 - DEBUG: Finished job 16 of 48: state/HepG2_20_segments/chr21
2020-08-13 16:49:55,210 - DEBUG: Finished job 17 of 48: state/HepG2_20_segments/chr22
2020-08-13 16:49:55,319 - DEBUG: Finished job 18 of 48: state/HepG2_20_segments/chr6
2020-08-13 16:49:55,373 - DEBUG: Finished job 19 of 48: state/HepG2_20_segments/chr16
2020-08-13 16:49:55,513 - DEBUG: Finished job 20 of 48: state/HepG2_20_segments/chr19
2020-08-13 16:49:55,632 - DEBUG: Finished job 21 of 48: state/HepG2_20_segments/chr17
2020-08-13 16:49:55,854 - DEBUG: Finished job 22 of 48: state/HepG2_20_segments/chr20
2020-08-13 16:49:56,001 - DEBUG: Finished job 23 of 48: state/K562_20_segments/chrX
2020-08-13 16:49:56,454 - DEBUG: Finished job 24 of 48: state/K562_20_segments/chr4
2020-08-13 16:49:56,472 - DEBUG: Finished job 25 of 48: state/K562_20_segments/chr13
2020-08-13 16:49:56,739 - DEBUG: Finished job 26 of 48: state/K562_20_segments/chr9
2020-08-13 16:49:56,803 - DEBUG: Finished job 27 of 48: state/K562_20_segments/chr5
2020-08-13 16:49:56,819 - DEBUG: Finished job 28 of 48: state/K562_20_segments/chr14
2020-08-13 16:49:56,955 - DEBUG: Finished job 29 of 48: state/K562_20_segments/chr8
2020-08-13 16:49:56,982 - DEBUG: Finished job 30 of 48: state/K562_20_segments/chr3
2020-08-13 16:49:57,125 - DEBUG: Finished job 31 of 48: state/K562_20_segments/chr10
2020-08-13 16:49:57,142 - DEBUG: Finished job 32 of 48: state/K562_20_segments/chr11
2020-08-13 16:49:57,213 - DEBUG: Finished job 33 of 48: state/K562_20_segments/chrY
2020-08-13 16:49:57,409 - DEBUG: Finished job 34 of 48: state/K562_20_segments/chr12
2020-08-13 16:49:57,486 - DEBUG: Finished job 35 of 48: state/K562_20_segments/chr7
2020-08-13 16:49:57,591 - DEBUG: Finished job 36 of 48: state/K562_20_segments/chr6
2020-08-13 16:49:57,616 - DEBUG: Finished job 37 of 48: state/K562_20_segments/chr18
2020-08-13 16:49:57,734 - DEBUG: Finished job 38 of 48: state/K562_20_segments/chr15
2020-08-13 16:49:57,802 - DEBUG: Finished job 39 of 48: state/K562_20_segments/chr21
2020-08-13 16:49:57,829 - DEBUG: Finished job 40 of 48: state/K562_20_segments/chr16
2020-08-13 16:49:57,837 - DEBUG: Finished job 41 of 48: state/K562_20_segments/chr20
2020-08-13 16:49:57,863 - DEBUG: Finished job 42 of 48: state/K562_20_segments/chr22
2020-08-13 16:49:58,294 - DEBUG: Finished job 43 of 48: state/K562_20_segments/chr17
2020-08-13 16:49:58,342 - DEBUG: Finished job 44 of 48: state/K562_20_segments/chr19
2020-08-13 16:50:01,017 - DEBUG: Finished job 45 of 48: state/HepG2_20_segments/chr1
2020-08-13 16:50:02,796 - DEBUG: Finished job 46 of 48: state/K562_20_segments/chr2
2020-08-13 16:50:03,257 - DEBUG: Finished job 47 of 48: state/HepG2_20_segments/chr2
2020-08-13 16:50:06,222 - DEBUG: Finished job 48 of 48: state/K562_20_segments/chr1
2020-08-13 16:50:06,315 - DEBUG: Saving metadata to output file
2020-08-13 16:50:06,335 - DEBUG: Estimated background state: 4 (100.0%)
2020-08-13 16:50:06,400 - DEBUG: All metadata saved
2020-08-13 16:50:06,486 - DEBUG: Output file closed - exiting...
2020-08-13 16:50:06,498 - DEBUG: Configuration written to my_path/sciddo/20200813-164952-pmip_SCIDDO_convert_cfg.json_

3. Now for the stats I run into the following problem:
<i>sciddo.py --debug --workers 16 stats -d HM_TF-SRSF1-PTBP1 -c -a
2020-08-13 16:50:30,460 - DEBUG: Configuration written to my_path/sciddo/20200813-165030-vtzh_SCIDDO_stats_cfg.json
2020-08-13 16:50:30,461 - DEBUG: Computing counting statistics...
2020-08-13 16:50:30,461 - DEBUG: Count statistics: state composition per sample
2020-08-13 16:50:30,614 - DEBUG: Created parameter list of length 48 to process
2020-08-13 16:50:31,775 - DEBUG: All counts collected, building data frames...
2020-08-13 16:50:31,812 - DEBUG: Stored counts /statistic/counts/composition/HepG2_20_segments
2020-08-13 16:50:31,840 - DEBUG: Stored counts /statistic/counts/composition/K562_20_segments
2020-08-13 16:50:31,857 - DEBUG: Count statistics: state composition per sample - done
2020-08-13 16:50:31,858 - DEBUG: Count statistics: state transitions between sample pairs
2020-08-13 16:50:31,865 - WARNING: No design matrix in dataset - treating all samples as singletons, resulting in an all-vs-all comparison.
2020-08-13 16:50:31,968 - DEBUG: Identified 24 chromosomes in dataset
2020-08-13 16:50:31,968 - DEBUG: Identified 1128 sample pairs for comparison: singletons
2020-08-13 16:50:32,009 - DEBUG: Created parameter list of size 27072 to process
2020-08-13 16:55:55,331 - DEBUG: All sample pairs processed
2020-08-13 16:55:55,332 - DEBUG: Total positions processed: 17417828136
2020-08-13 16:55:55,333 - DEBUG: Thereof, identical positions: 12522689256 (71.9%)
2020-08-13 16:55:55,333 - DEBUG: Thereof, variable positions: 4895138880 (28.1%)
2020-08-13 16:55:55,391 - DEBUG: Stored transition counts for comparison / chromosome: /statistic/counts/transitions/singletons/chr13
Traceback (most recent call last):
  File "/nfs/home/students/ga89koc/.conda/envs/sciddo/lib/python3.6/site-packages/scidlib-0.8.0-py3.6-linux-x86_64.egg/EGG-INFO/scripts/sciddo.py", line 156, in <module>
    exc = cli_args.execute(cli_args, logger)
  File "/nfs/home/students/ga89koc/.conda/envs/sciddo/lib/python3.6/site-packages/scidlib-0.8.0-py3.6-linux-x86_64.egg/scidlib/cmd_stats.py", line 389, in _run_cmd_stats
    compute_pair_state_transitions(args, logger)
  File "/nfs/home/students/ga89koc/.conda/envs/sciddo/lib/python3.6/site-packages/scidlib-0.8.0-py3.6-linux-x86_64.egg/scidlib/cmd_stats.py", line 269, in compute_pair_state_transitions
    assert count_total == total_pos, 'Missing counts, expected {} but stored {}'.format(total_pos, count_total)
AssertionError: Missing counts, expected 17417828136 but stored 13122860840
2020-08-13 16:55:55,441 - ERROR: Properly handled shutdown upon error: </br>
Missing counts, expected 17417828136 but stored 13122860840
2020-08-13 16:55:55,441 - DEBUG: Run configuration stored at: my_path/sciddo/20200813-165030-vtzh_SCIDDO_stats_cfg.json<i>

Do you have any idea how I can handle that? I am not sure about the error message.
I am happy to supply more information if needed. :)

Thank you in advance.
Best,
Quirin

**Comment by ptrebert** [comment]
Hi Quirin,
sorry, the notification for this issue went by unnoticed - how large is the SCIDDO data file? Could you simply share that?
Best,
Peter

**Comment by quirinmanz** [comment]
Hi Peter,
thank you for your answer!

After the convert command the sciddo file is 16.1 mb large.

Best,
Quirin

**Comment by ptrebert** [comment]
Ok, that is certainly small enough - can you upload that to some cloud share and sent me the download link?

**Comment by quirinmanz** [comment]
Sure: https://drive.google.com/file/d/1Uaf9tiF1l4weMy_h_KFzxJKzCbntl8fb/view?usp=sharing
Would you tell as soon as you downloaded it so I can delete it?

**Comment by ptrebert** [comment]
done

**Comment by ptrebert** [comment]
fixed - this line in the debug log gives it away...
```
 2020-08-13 16:50:31,968 - DEBUG: Identified 1128 sample pairs for comparison: singletons
```
For singletons, the sample pair generating function had a bug and generated silly values. Please use latest commit from dev branch

**Comment by quirinmanz** [comment]
Thank you very much, it worked!

One small suggestion:
When score -ads "emission" is used I had to specify scan -sc "penem" and scan -sc "emmision" did not work. This is not huge but a little bit confusing.

Best, Quirin
